name: Deployment

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone app from master branch
        uses: actions/checkout@v2

      - name: Generate frontend .env
        run: |
          cat >> ./src/nextjs-front/.env << END
          NEXT_PUBLIC_FT_CLIENT_ID=$NEXT_PUBLIC_FT_CLIENT_ID
          NEXT_PUBLIC_FT_REDIRECT_URI=$NEXT_PUBLIC_FT_REDIRECT_URI
          NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
          END
        env:
          NEXT_PUBLIC_FT_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_FT_CLIENT_ID }}
          NEXT_PUBLIC_FT_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_FT_REDIRECT_URI }}
          NEXT_PUBLIC_SOCKET_URL: ${{ secrets.NEXT_PUBLIC_SOCKET_URL }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_API_KEY }}

      - name: Build Front
        uses: docker/build-push-action@v2
        with:
          context: ./src/nextjs-front
          tags: busshi/transcendance_front:latest
          platforms: |-
            linux/arm64
            linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha

      - name: Build Back
        uses: docker/build-push-action@v2
        with:
          context: ./src/nestjs-back
          tags: busshi/transcendance_back:latest
          platforms: |-
            linux/arm64
            linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha


  deploy:
    runs-on: ubuntu-20.04
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >> ~/.ssh/config << END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER  
            Port $SSH_PORT
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Deploy
        run: |
          ssh deploy 'make -C $HOME/my_transcendance deploy'

    needs: build
